/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NewsItem {
  'headline' : string,
  'summary' : string,
  'timestamp' : Time,
  'category' : string,
}
export interface PlayerCard {
  'username' : string,
  'wins' : bigint,
  'losses' : bigint,
  'score' : bigint,
  'avatarColor' : string,
}
export interface RobloxGame {
  'title' : string,
  'description' : string,
  'playersOnline' : bigint,
  'genre' : string,
  'topScore' : bigint,
}
export interface ScoreboardEntry {
  'participants' : string,
  'score' : string,
  'matchName' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllNewsItems' : ActorMethod<[], Array<NewsItem>>,
  'getAllPlayerCards' : ActorMethod<[], Array<PlayerCard>>,
  'getAllRobloxGames' : ActorMethod<[], Array<RobloxGame>>,
  'getAllScoreboardEntries' : ActorMethod<[], Array<ScoreboardEntry>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];