/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const NewsItem = IDL.Record({
  'headline' : IDL.Text,
  'summary' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
});
export const PlayerCard = IDL.Record({
  'username' : IDL.Text,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'score' : IDL.Nat,
  'avatarColor' : IDL.Text,
});
export const RobloxGame = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'playersOnline' : IDL.Nat,
  'genre' : IDL.Text,
  'topScore' : IDL.Nat,
});
export const ScoreboardEntry = IDL.Record({
  'participants' : IDL.Text,
  'score' : IDL.Text,
  'matchName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getAllPlayerCards' : IDL.Func([], [IDL.Vec(PlayerCard)], ['query']),
  'getAllRobloxGames' : IDL.Func([], [IDL.Vec(RobloxGame)], ['query']),
  'getAllScoreboardEntries' : IDL.Func(
      [],
      [IDL.Vec(ScoreboardEntry)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const NewsItem = IDL.Record({
    'headline' : IDL.Text,
    'summary' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
  });
  const PlayerCard = IDL.Record({
    'username' : IDL.Text,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'score' : IDL.Nat,
    'avatarColor' : IDL.Text,
  });
  const RobloxGame = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'playersOnline' : IDL.Nat,
    'genre' : IDL.Text,
    'topScore' : IDL.Nat,
  });
  const ScoreboardEntry = IDL.Record({
    'participants' : IDL.Text,
    'score' : IDL.Text,
    'matchName' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllNewsItems' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getAllPlayerCards' : IDL.Func([], [IDL.Vec(PlayerCard)], ['query']),
    'getAllRobloxGames' : IDL.Func([], [IDL.Vec(RobloxGame)], ['query']),
    'getAllScoreboardEntries' : IDL.Func(
        [],
        [IDL.Vec(ScoreboardEntry)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };